server:
  port: 8082
# logging
logging:
  config: classpath:logback-spring.xml
# mybatis
mybatis:
  typeAliasesPackage: com.example.entity
  mapper-locations: classpath*:mapper/*.xml

# MyBatisPlus配置
# https://baomidou.com/config/
mybatis-plus:
  # 多包名使用 例如 cn.bds.**.mapper,org.xxx.**.mapper
  mapperPackage: com.**.mapper
  # 对应的 XML 文件位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.**.domain
  #  configuration:
  #    # 更详细的日志输出 会有性能损耗 org.apache.ibatis.logging.stdout.StdOutImpl
  #    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    dbConfig:
      # 主键类型
      # AUTO 自增 NONE 空 INPUT 用户输入 ASSIGN_ID 雪花 ASSIGN_UUID 唯一 UUID
      # 如需改为自增 需要将数据库表全部设置为自增
      idType: ASSIGN_ID
      # 逻辑已删除值
      logicDeleteValue: 1
      # 逻辑未删除值
      logicNotDeleteValue: 0
  configuration:
    # MyBatis 自动映射时未知列或未知属性处理策
    # NONE：不做处理 WARNING：打印相关警告 FAILING：抛出异常和详细信息
    autoMappingUnknownColumnBehavior: NONE
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:shardingsphere:classpath:sharding-tables.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
subDb:
  dbName: BDS_SUB_DB
  driverClassName: ${SUB_DB_DRIVER_CLASS_NAME:dm.jdbc.driver.DmDriver}
  jdbcUrl: ${SUB_DB_JDBC_URL:jdbc:dm://192.168.10.240:5236/BDS_SUB_DB}
  username: ${SUB_DB_USERNAME:SYSDBA}
  password: ${SUB_DB_PASSWORD:Bfz@1314.}