server:
  port: 8082
# logging
logging:
  config: classpath:logback-spring.xml
# mybatis
mybatis:
  typeAliasesPackage: com.example.entity
  mapper-locations: classpath*:mapper/*.xml
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:shardingsphere:classpath:sharding-tables.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver